version: '3.7'

services:
  dash:
    build:
      context: .
      dockerfile: Dockerfile.dash
    image: dash:$VERSION
    container_name: dash
    ports:
      - "80:5050"
    environment:
      - TARGET=$TARGET
    restart: unless-stopped